Add file to CR
AvtoBBus/Bus_Station_15 pull request #1
Opened 2023-10-21 04:55 UTC by AvtoBBus

2023-10-21 05:46 UTC, AvtoBBus reviewed
Общее замечание почти везде отсутствуют докстринги

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +def create_lift_pass_db_connection(connection_options):
отсутствует tipe-hinting

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    for fun in connection_functions:
fun не совсем говорящее название для переменной

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +            print(f"unable to connect to db with {fun}")
Ошибка отлавливается, однако не выводится её содержание

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +def try_to_connect_with_sqlite3(connection_options):
нет тайп-хинт

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    ]
24 - 37 строчки хард код, лучше записать тогда в файл и из него считывать

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    import sqlite3
импорты обычно делаются в начале файла

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    import pymysql.cursors
импорты обычно делаются в начале файла

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    class PyMySQLCursorWrapper(pymysql.cursors.Cursor):
класс внутри функции....

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +        import pyodbc
импорты обычно в начале файла делаются

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +def try_to_connect_with_odbc(connection_options):
нет тайп-хинт

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +def try_to_connect_with_pymysql(connection_options):
нет тайп-хинт

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    import pyodbc
импорты обычно в начале файла делаются

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +def get_mariadb_driver():
нет тайп-хинт

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    else:
можно сделать тернарным или просто убрать else

2023-10-21 05:46 UTC, AvtoBBus commented on db.py
> +    return 'DRIVER={' + driver + '};SERVER=%s;USER=%s;OPTION=3;DATABASE=%s;PASSWORD=%s'
сделать f-строкой для читабельности

2023-10-21 05:46 UTC, AvtoBBus commented on prices.py
> +connection_options = {
можно было бы сохранять в json файл и после из него считывать

2023-10-21 05:46 UTC, AvtoBBus commented on prices.py
> +    global connection
нет необходимости в создании глобальной переменной

2023-10-21 05:46 UTC, AvtoBBus commented on prices.py
> +        cursor = connection.cursor()
cursor можно создавать перед if в 24 строчке ибо эта переменная используется в обоих случаях выполнения программы

2023-10-21 05:46 UTC, AvtoBBus commented on prices.py
> +        cursor.execute('INSERT INTO `base_price` (type, cost) VALUES (?, ?) ' +
хард-код лучше сделать в переменной

2023-10-21 05:46 UTC, AvtoBBus commented on prices.py
> +                       + 'WHERE type = ? ', (request.args['type'],))
хард-код лучше сделать в переменной

2023-10-21 05:46 UTC, AvtoBBus commented on prices.py
> +                    if 'age' not in request.args:
можно было бы сне делать else а затем проверять условия, а сразу сделать в elif

2023-10-21 05:46 UTC, AvtoBBus commented on test_prices.py
> +TEST_PORT = 3006
лучше сохранить в отдельный файл типо setting.json

2023-10-21 05:46 UTC, AvtoBBus commented on test_prices.py
> +def server(port):
в этой функции нет смысл ибо она лишь запускает приложение, это лучше добавить в if __name__

2023-10-21 05:46 UTC, AvtoBBus commented on test_prices.py
> +def wait_for_server_to_start(server_url):
нет тайп-хинт

2023-10-21 05:46 UTC, AvtoBBus commented on test_prices.py
> +            time.sleep(0.2)
если ошибка отлавливает то пусть выводится или логируется

2023-10-21 05:46 UTC, AvtoBBus commented on test_prices.py
> +    server_url = f"http://127.0.0.1:{TEST_PORT}"
хард-код, можно как и TEST_PORT сохранить в setting.json

2023-10-21 05:46 UTC, AvtoBBus commented on test_prices.py
> +def test_something(lift_pass_pricing_app):
нет тайп-хинт

2023-10-21 07:26 UTC, alxmcs requested changes

2023-10-21 07:26 UTC, alxmcs commented on db.py
Для этого модуля хотелось бы почитать в ревью предложения по декомпозиции кода, чтобы обойтись без импорта провайдеров в разные субд в функциях. Этот код, в целом, можно легко растащить по разным сущностям так, чтобы:
* не было импортировать либы всех субд на свете
* работа с бд все еще оставалась прозрачна для пользователя
Так что хотелось бы увидеть твои идеи по этому поводу.

2023-10-21 07:26 UTC, alxmcs commented on prices.py
> +        cursor.execute('INSERT INTO `base_price` (type, cost) VALUES (?, ?) ' +
Здесь стоит обратить внимание на то, что это sql кваери, а работа с бд у нас вроде как вытащена в соседний модуль

2023-10-21 07:26 UTC, alxmcs commented on prices.py
Для этого модуля я бы хотел почитать о том, как избавиться от bumpy road и снизить лютейшую цикломатическую сложность этого полотнища кода. И как распилить это полотнище на функции/классы, чтобы код стал доступным для понимания и для обычного человека, а не только для ксеноса с тремя мозгами.

2023-10-31 08:16 UTC, AvtoBBus commented on db.py
Как Вы и указали, я бы растащил функции, работающие с СУБД по разным модулям, а тот класс, объявленный внутри функции, так же выделил бы в отдельный модуль. Таким образом будет 4 модуля, каждый из которых будет реюзабелен, и работа с БД также остаётся прозрачной для пользователя

2023-10-31 08:27 UTC, AvtoBBus commented on prices.py
Как вариант распиления на функции, это выделить в отдельные если не модули, то хотя бы func моменты после if requests.method, условно сделать две функции put_method и get_method

2023-10-31 08:31 UTC, AvtoBBus commented on prices.py
Для уменьшения цикломатической сложности, можно все проверки что содержат request.args или подобное разделить на отдельные функции, то есть если. к примеру 'age' in requests.args, то мы прыгаем в одну функцию, которая выполняет необходимые проверки линейно, те без else, чисто if-ми

2023-10-31 08:32 UTC, AvtoBBus reviewed
В целом очень многие части кода необходимо разнести по функциям

2023-10-31 09:36 UTC, alxmcs approved these changes
Зачтено

2023-10-31 09:37 UTC, closed without merging